<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Command line suite]" verbose="0">
  <test thread-count="5" name="Command line test(failed)" verbose="0">
    <classes>
      <class name="com.automation.testcases.DivTest">
        <methods>
          <include name="divTest" invocation-numbers="4"/>
        </methods>
      </class> <!-- com.automation.testcases.DivTest -->
      <class name="com.automation.testcases.DataDrivenTest">
        <methods>
          <include name="verifyLoginUnsuccessfulWithInvalidCredentials" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.automation.testcases.DataDrivenTest -->
      <class name="com.automation.testcases.LoginTest">
        <methods>
          <include name="setUp"/>
          <include name="verifyUserCanLogin"/>
          <include name="cleanUp"/>
        </methods>
      </class> <!-- com.automation.testcases.LoginTest -->
    </classes>
  </test> <!-- Command line test(failed) -->
</suite> <!-- Failed suite [Command line suite] -->
